                        ############################################
                        #----------------API Docs------------------#
                        #                                          #
                        #  Begin  _ Mar 5, 2024                    #
                        #  Finish _                                #
                        #  Author _ Luka Danelia                   #
                        ############################################


# This must be first request to create company in db
# Then it receivs activation email
# @body _ ICompanyRequest

# p.s. 
# for siplicity im not encrypting passwords here, but store hash in db 
# in prod environment everything must be encrypted
POST  http://localhost:3000/api/auth/registration
Content-Type: application/json

{
    "companyName": "Microsoft",
    "email": "luka.danelia268@eab.tsu.edu.ge",
    "country": "Georgia",
    "password":"SOMEPASS",
    "industry":"IT"
}
########################################################################################
########################################################################################


# User will receive activation email
# After proceeding to url company gets activated
# works only once
# @param _ companyId
GET http://localhost:3000/api/auth/activate/?id=<param>
Content-Type: application/json
########################################################################################
########################################################################################

# activates employee account
GET http://localhost:3000/api/auth/activate-employee/?employeeId=6&password=pass
Content-Type: application/json
########################################################################################
########################################################################################

# GET COMPANY TOKEN
# USE THAT TOKEN IN EVERY OTHER REQUEST
# TOKEN LIFECYCLE IS SERVER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"luka.danelia268@eab.tsu.edu.ge",
    "password":"NEWPASS"
}
########################################################################################
########################################################################################

# GET EMPLOYEE TOKEN
# USE THAT TOKEN IN EVERY OTHER REQUEST
# TOKEN LIFECYCLE IS SERVER
POST http://localhost:3000/api/auth/login-employee
Content-Type: application/json

{
    "username":"lukito",
    "password":"pass"
}

########################################################################################
########################################################################################

@token= "SEV2uXX/XB7Nk1SQa2BcYaTOi+jRDs93mfTmf+a/lvfmxQRXCHt6TfnqhEqtsr3uMhb9JReOLDdWf+w3dhdP0I+hAfGYXlrOc17vUDSZgDmusYddVj9jJTiSl0ECDbQrow1YBDO5zOFfGbeUeOs3p+zltYCb8JMWEqKTcyWT+xQEjPZ6T2jBJj5W+or67cnewsAoRgeeyaKiBtQb4jGTSUn8ZgoiXgiITuPDREtMuRLY2IW7uh4j5kiLttEVyG33tjiMzYPwKyT3svMOP8iLg4jXtH/9pAWBJA026llMQlwNQJ4K+LBqVSDoQQ+HFpz0/CWP9ZNe/05qjbBwru4hQg=="


# Simply changes password
PUT http://localhost:3000/api/content/change/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "newPassword":"NEWPASS"
}
########################################################################################
########################################################################################

# plan must be either [Free,Basic,Premium]
POST http://localhost:3000/api/content/change/subscription
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "plan":"Premium" 
}
########################################################################################
########################################################################################

# change company's personal informaion
POST http://localhost:3000/api/content/change/copmany-information
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "companyName":"HELLO",
    "email":"luka.danelia268@eab.tsu.edu.ge",
    "country":"georgia",
    "industry":"it"
}
########################################################################################
########################################################################################

# adds new employee in db
# sends activation email 
POST http://localhost:3000/api/content/add/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username":"lukito",
    "email":"luka.danelia@ugt.ge",
    "isAdmin":"false"
}
########################################################################################
########################################################################################

# Exposes information for admin as @IEmployeeList[]
# Requires login as user, not compnay
GET http://localhost:3000/api/content/employee-list
Content-Type: application/json
Authorization: Bearer {{token}}

########################################################################################
########################################################################################

# Removes empployee from list
DELETE http://localhost:3000/api/content/delete/employee/?employeeId=<>
Content-Type: application/json
Authorization: Bearer {{token}}
########################################################################################
########################################################################################

# upload new document in file system
#
POST http://localhost:3000/api/content/upload/file/?all=false&employees=[9,7]
Content-Type: multipart/form-data
Authorization: Bearer {{token}}

file

########################################################################################
########################################################################################

# Changes visibility for certain fil
# Accesible only for author employee
PUT http://localhost:3000/api/content/change/visibility/?all=<true|false>&employees=<[empId]>&fileId=<fileId>
Content-Type: application/json
Authorization: Bearer {{token}}
########################################################################################
########################################################################################

# Deletes file record
# Accesible only for author employee
DELETE http://localhost:3000/api/content/delete/file/?fileId=<fileId>
Content-Type: application/json
Authorization: Bearer {{token}}
########################################################################################
########################################################################################

# Login as company
GET http://localhost:3000/api/subscription/current-billing
Content-Type: application/json
Authorization: Bearer {{token}}

########################################################################################
########################################################################################
