                        ############################################
                        #----------------API Docs------------------#
                        #                                          #
                        #  Begin  _ Mar 5, 2024                    #
                        #  Finish _                                #
                        #  Author _ Luka Danelia                   #
                        ############################################


# This must be first request to create company in db
# Then it receivs activation email
# @body _ ICompanyRequest

# p.s. 
# for siplicity im not encrypting passwords here, but store hash in db 
# in prod environment everything must be encrypted
POST  http://localhost:3000/api/auth/registration
Content-Type: application/json

{
    "companyName": "Microsoft",
    "email": "luka.danelia268@eab.tsu.edu.ge",
    "country": "Georgia",
    "password":"SOMEPASS",
    "industry":"IT"
}
########################################################################################
########################################################################################


# User will receive activation email
# After proceeding to url company gets activated
# works only once
# @param _ companyId
GET http://localhost:3000/api/auth/activate/?id=<param>
Content-Type: application/json
########################################################################################
########################################################################################

# activates employee account
#************************************************#*********   UNDONE  *********#************************************************
#************************************************#*********   UNDONE  *********#************************************************
GET http://localhost:3000/api/auth/activate/?id=<employeeId>&password=<password>
Content-Type: application/json
########################################################################################
########################################################################################

# GET TOKEN
# USE THAT TOKEN IN EVERY OTHER REQUEST
# TOKEN LIFECYCLE IS SERVER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"luka.danelia268@eab.tsu.edu.ge",
    "password":"NEWPASS"
}
########################################################################################
########################################################################################

#************************************************#*********   UNDONE  *********************#************************************************
#************************************************#*********   UNDONE  *********************#************************************************
POST http://localhost:3000/api/auth/login-employee
Content-Type: application/json

{
    "username":"",
    "password":""
}

########################################################################################
########################################################################################

@token="UPoHhZl/N0e7h3+gRxwz/3mGvYzAlUqcDZb0WzjNTYjnMRkhkUmJFMOmQU6RO0GqfHLfT4B/MfLaLDhi9Q4JljWdJlLCpWdvfmQh/eVTmcCj06J7mL0aOyYJ2rbKQulBVErXXZAyTGhU+6IBet3aA5Ml0pXk9YktY1F5XgmXEG3IzDLIDgsFsJ0vcf7cfbkDG/7EysXSYg2KIws/lQL5XCIr8A1ZrqFJiVIYZG+SSNVkdScFaHH8awEbu826+HyIA+qMPNlOk79qZ2TLS+WXAPkZ2+KFh0pPRc8HztqJfHoV3Af+km8fw52Zh/8BEjFtfvlq2swrG/vwfWa/OKafwQ=="


# Simply changes password
PUT http://localhost:3000/api/content/change/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "newPassword":"NEWPASS"
}
########################################################################################
########################################################################################

# plan must be either [Free,Basic,Premium]
POST http://localhost:3000/api/content/change/subscription
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "plan":"Premium" 
}
########################################################################################
########################################################################################

# change company's personal informaion
POST http://localhost:3000/api/content/change/copmany-information
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "companyName":"vau",
    "email":"luka.danelia268@eab.tsu.edu.ge",
    "country":"georgia",
    "industry":"it"
}
########################################################################################
########################################################################################

# adds new employee in db
# sends activation email 
POST http://localhost:3000/api/content/add/employee
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username":"lukito",
    "email":"luka.danelia@ugt.ge",
    "isAdmin":"false"
}
########################################################################################
########################################################################################
